spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 7735c3f5847350bf19b87bea56fe8869
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname